### ISSUE TITLE
BUG // wrong wording when changing navigation tabs

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/ckanext-odm_library#18]
https://pp-data.opendevelopmentmekong.net/dataset/f53e97bf-a392-59ea-85d3-01dd6f03778b

when you are on library-dataset-page – clicking on "groups" changes the wording of the "library record" link to "dataset"

expected behaviour:
--> wording shouldn't change >> use library record

**Comment by acorbi** [comment]
This is fixed now
