### ISSUE TITLE
Define explanatory texts for the library

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_library#2]
As depicted in the screenshot below, now we have a customize area were we can explain users about the library records.

**Comment by t-parnell** [comment]
Library records provide all the bibliographical information or metadata needed to help users find the documents most appropriate to their needs. 
Certain fields on this form are mandatory.  Your library record cannot be uploaded without providing information in those fields.
Please provide as much information as possible, even when fields are not mandatory. If you need more guidance on how to do this please see WIKI. 
Once you have completed the form, plse check to make sure it is accurate and complete. 
Your recommended library item will be made available to the public once your library record has been vetted.

**Comment by acorbi** [comment]
This has been already fixed, now these instructions are available on the wiki
