### ISSUE TITLE
Document type "company profile" to be deleted.

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_library#49]
@acorbi -- I've looked through these records and mostly they are assigned the wrong document type. The majority I went through were actually "archive web content" from different sources, and there were a few that were reports an simply not allocated correctly. 

Best would be to convert all these to "archive web content" and have someone go through them all to correct anything else. The issue with this document type is that many of the pdf's created don't have a date of when they were created so it's difficult to validate the information in time. I will discuss with ODC.

**Comment by prustar** [comment]
@acorbi -- I just uploaded the new record for library document types san 'company profile'. 
https://data.staging.opendevelopmentmekong.net/dataset/odm-library-resources-document-types 
Please apply when you can.

**Comment by acorbi** [comment]
@prustar the plan is to:

1. Migrate all those 261 records marked as 'company profile' and change them to 'archived_web_content'
2. Have somebody go through those records and make sure data is consistent

correct? Please confirm and I'll take care of it.

Also, I noticed that there are also other types of profiles on that list of document types: 'Profiles - People', 'Profiles - Organizations and projects' and 'Profiles - Geographical areas and sites'. 

Does it then make sense to keep them while we are deleting the 'company profiles' type?

**Comment by prustar** [comment]
@acorbi Where are these tags? I didn't ever see these in CKAN as document types previously? 

This has been a critique of ODC profiles for a long time now raised by many researchers past and present. The tagging system is not appropriate as what it brings up is not what people expect. Have these options always been available? It's not a good way to organise the data and I need to speak to them about it. I'll update you tomorrow.

**Comment by prustar** [comment]
@acorbi -- these options were added don't know when but the wiki does not list them as options.

**Comment by acorbi** [comment]
Well, they are available on the form for creating a new **library record** -> https://data.staging.opendevelopmentmekong.net/library_record/new

![screenshot from 2016-12-20 11-13-47](https://cloud.githubusercontent.com/assets/384894/21346679/a789bfb0-c6a5-11e6-945e-5d9f38864b62.png)

That field pulls its values form the corresponding data table: https://data.staging.opendevelopmentmekong.net/dataset/odm-library-resources-document-types/resource/841caec7-73d2-4424-9727-0b599ad9cff8?type=dataset that you created. We should then remove them from there. you can use Libreoffice Base for that.

> Have these options always been available? It's not a good way to organise the data and I need to speak to them about it. I'll update you tomorrow.

I guess so. Please do and confirm me when I can do the migration.

**Comment by prustar** [comment]
related to issue: https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/381
